version: '1'
services:
  app:
    container_name: "spring_app"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local_docker
networks:
  local_docker: