version: '1'
services:
  db:
    image: "mysql:latest"
    restart: unless-stopped
    hostname: "db"
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3307"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db