spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cors:
  allow-origin: http://10.37.129.2:3000, http://localhost:5173

jwt:
  secret: dadadadafajfkhajkdhakdhajkfdhalkdhjkadhajkfkahdsjkadhjkadhsajkfhajkdhajkdhajkdj