spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cors:
  allow-origin: http://192.168.50.103:3000, http://localhost:5173, http://localhost:3000

jwt:
  secret: dadadadafajfkhajkdhakdhajkfdhalkdhjkadhajkfkahdsjkadhjkadhsajkfhajkdhajkdhajkdj